#!/usr/bin/env bash
# Vendor the built mermaid diagram bundle into the theme and record its
# provenance. Hugo modules serve theme files straight from the git repo, so
# the theme cannot depend on the package at runtime; the built output has to
# be committed. This script is the only supported way to update that copy.
set -euo pipefail

SRC_DIR="${1:-../mermaid-doodle}"
SRC_FILE="$SRC_DIR/dist/auto.iife.js"

if [ ! -f "$SRC_FILE" ]; then
  echo "error: no built bundle at $SRC_FILE" >&2
  echo "build the package first, or pass its checkout path as \$1" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST_FILE="$ROOT/assets/js/lib/mermaid-doodle.iife.js"
RECORD_FILE="$DEST_FILE.provenance"

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

VERSION="unknown"
if [ -f "$SRC_DIR/package.json" ]; then
  VERSION="$(grep -m1 '"version"' "$SRC_DIR/package.json" | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
fi

COMMIT="unknown"
if git -C "$SRC_DIR" rev-parse HEAD >/dev/null 2>&1; then
  COMMIT="$(git -C "$SRC_DIR" rev-parse HEAD)"
fi

cp "$SRC_FILE" "$DEST_FILE"
SHA256="$(sha256_of "$DEST_FILE")"

cat > "$RECORD_FILE" <<EOF
# Provenance for the vendored diagram bundle at mermaid-doodle.iife.js.
# Regenerated by scripts/vendor-mermaid-doodle.sh. Do not hand edit.
SOURCE_VERSION=$VERSION
SOURCE_COMMIT=$COMMIT
SHA256=$SHA256
EOF

echo "vendored $SRC_FILE -> $DEST_FILE"
echo "  source version: $VERSION"
echo "  source commit:  $COMMIT"
echo "  sha256:         $SHA256"
