#!/usr/bin/env bash
# Vendor the built mermaid diagram bundle into the theme and record its
# provenance. Hugo modules serve theme files straight from the git repo, so
# the theme cannot depend on the package at runtime; the built output has to
# be committed. This script is the only supported way to update that copy.
#
# Defaults to the mermaid-doodle package installed under node_modules (run
# `npm install` first to fetch the version pinned in package.json). Pass a
# local checkout or build path as $1 to vendor from an unreleased build
# instead, for testing changes before they are published.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="${1:-$ROOT/node_modules/mermaid-doodle}"
SRC_FILE="$SRC_DIR/dist/auto.iife.js"

if [ ! -f "$SRC_FILE" ]; then
  echo "error: no built bundle at $SRC_FILE" >&2
  echo "run 'npm install' to fetch the pinned package, or pass a local checkout/build path as \$1" >&2
  exit 1
fi

DEST_FILE="$ROOT/assets/js/lib/mermaid-doodle.iife.js"
RECORD_FILE="$DEST_FILE.provenance"

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

VERSION="unknown"
if [ -f "$SRC_DIR/package.json" ]; then
  VERSION="$(grep -m1 '"version"' "$SRC_DIR/package.json" | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
fi

COMMIT="unknown"
# Only trust this as a source commit when SRC_DIR is itself a git checkout
# (has its own .git). A node_modules copy has none, and without this check
# `git -C` would walk up to this theme's own .git and report the theme's
# HEAD as if it were the source commit.
if [ -e "$SRC_DIR/.git" ] && git -C "$SRC_DIR" rev-parse HEAD >/dev/null 2>&1; then
  COMMIT="$(git -C "$SRC_DIR" rev-parse HEAD)"
fi

# The version pinned in this repo's own package.json, independent of which
# SRC_DIR the bundle was actually copied from. For the default node_modules
# source this matches VERSION above; when vendoring from a local unreleased
# checkout it still records which published version this repo is pinned to.
NPM_VERSION="unknown"
if grep -q '"mermaid-doodle"' "$ROOT/package.json" 2>/dev/null; then
  NPM_VERSION="$(grep -m1 '"mermaid-doodle"' "$ROOT/package.json" | sed -E 's/.*"mermaid-doodle": *"([^"]+)".*/\1/')"
fi

cp "$SRC_FILE" "$DEST_FILE"
SHA256="$(sha256_of "$DEST_FILE")"

cat > "$RECORD_FILE" <<EOF
# Provenance for the vendored diagram bundle at mermaid-doodle.iife.js.
# Regenerated by scripts/vendor-mermaid-doodle.sh. Do not hand edit.
SOURCE_VERSION=$VERSION
SOURCE_COMMIT=$COMMIT
NPM_VERSION=$NPM_VERSION
SHA256=$SHA256
EOF

echo "vendored $SRC_FILE -> $DEST_FILE"
echo "  source version: $VERSION"
echo "  source commit:  $COMMIT"
echo "  npm pin:        $NPM_VERSION"
echo "  sha256:         $SHA256"
